[1-2] FastAPI로 게시글 REST API 서버 구현하기 - UD 엔드포인트 구현
f-lab-edu/fastapi-post pull request #1
Opened 2024-06-29 12:39 UTC by ksg9482

* pre-commit, black, isort, pycln을 설정해서 commit 전에 자동 포맷팅 하도록 설정했습니다.
* jwt를 이용해서 포스트 작성자만 update, delete에 접근 가능하도록 했습니다.
* 작성자와 포스트의 관계성을 확실히 하기 위해서 user 도메인을 구성했습니다.

2024-06-30 11:54 UTC, f-lab-ydrah requested changes
코멘트 확인 해주세요~

2024-06-30 11:54 UTC, f-lab-ydrah commented on README.md
> -poetry install
의존성 설치를 위해 `poetry install` 는 한번 해야하지 않을까요?

`uvicorn main.py` 은 실행 부분에 들어가야 할거 같습니다.

2024-06-30 11:54 UTC, f-lab-ydrah commented on pyproject.toml
> +package-mode = false
이걸 `false` 로 주면 어떤 차이를 불러 일으키나요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/auth.py
> +def encode_access_token(data: dict, expires_delta: timedelta) -> dict:
```suggestion
def encode_access_token(data: dict, expires_delta: timedelta) -> dict[str, str]:
```

위처럼 key, value 에도 타입을 명시하는게 좋습니다.

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/database.py
> +engine = AsyncEngine(create_engine(DATABASE_URL, echo=True, future=True))
`future=True` 로 주면 어떻게 달라지나요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/database.py
> +    yield
인메모리 구성이라, `drop` 하는 부분은 필요없지 않을까요?
굳이 넣으신 이유가 있으실까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/middlewares.py
> +            {"detail": "Token is required"}, status_code=status.HTTP_401_UNAUTHORIZED
`fastapi.status` 모듈 쓰신거 너무 좋습니다. 명시적이고 시멘틱해요.

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/models/post.py
> +    user: User = Relationship(back_populates="posts")
`author` 와 `user_id` 둘 다 있는걸까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/models/user.py
> +    posts: list["Post"] = Relationship(back_populates="user")
이러면 `user` 를 불러올 때마다 `posts` 데이터도 같이 불러오지 않을까요?
필요없는 쿼리가 과하게 실행되지는 않을까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +    author = request.state.user["name"]
이 방식의 장점과 단점은 무엇일까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +    await session.commit()
`await` 을 하면 어떤 일이 벌어질까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +    post = result.one()
만약에 `post_id` 에 해당하는 데이터가 없으면 어떤 일이 벌어질까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="존재하지 않는 포스트입니다"
`400` 보다 더 적절한 상태 코드는 없을까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +        .join(UserModel, PostModel.user_id == UserModel.id)
조인을 하지 않고 해결할 수 있는 방법은 없을까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +    if post == None:
```suggestion
    if not post:
```

보통 위처럼 표현하는게 좀 더 파이썬 스럽습니다.

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +            status_code=status.HTTP_400_BAD_REQUEST,
인가에 문제가 있을 때, 400보다 더 적절한 상태 코드는 무엇일까요

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/post.py
> +    await session.delete(post)
혹시 소프트 delete와 그냥 delete의 차이를 아실까요?
언제 소프트 delete를 쓰면 좋을까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/routers/user.py
> +        raise HTTPException(status_code=400, detail="Invalid password")
메시지는 한글, 영어 둘 중 하나로 통일하면 일관성이 있을거 같습니다.

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/schemas/post.py
> +    created_at: Optional[datetime] = None
업데이트 되는 경우를 생각해서 `updated_at` 도 추가하는건 어떨까요?

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/schemas/user.py
> +class Login(BaseModel):
```suggestion
class LoginRequest(BaseModel):
```

위처럼 API Request, Response 임을 클래스 이름에 명시해주는게 좀 더 명시적이고 시멘틱해보입니다.

2024-06-30 11:54 UTC, f-lab-ydrah commented on src/schemas/user.py
> +class User(BaseModel):
```suggestion
class SignupRequest(BaseModel):
```

위처럼 API Request, Response 임을 클래스 이름에 명시해주는게 좀 더 명시적이고 시멘틱해보입니다.

2024-07-01 05:04 UTC, ksg9482-kouno reviewed
좀 늦었지만 코멘트 확인했습니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on README.md
> -poetry install
네. README에 설치 및 실행부분 재작성하겠습니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on pyproject.toml
> +package-mode = false
poetry는 패키지 관리자이자 의존성 관리자로 package mode는 poetry를 패키징에도 사용하는지, 의존성관리에만 사용하는지를 결정합니다. false로 하면 패키징을 실행하지 않고 의존성만 관리하게 됩니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/auth.py
> +def encode_access_token(data: dict, expires_delta: timedelta) -> dict:
네. 알겠습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/database.py
> +engine = AsyncEngine(create_engine(DATABASE_URL, echo=True, future=True))
future는 SQLAlchemy의 최신인 1.4, 2.0을 따른다는 의미입니다. 확인해보니 6/18에 2.0이 릴리즈 되었네요

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +    author = request.state.user["name"]
장점은 이미 미들웨어에서 유저를 삽입해주기 때문에 유저정보를 각 비즈니스 로직에서 처리하지 않아도 되는 점입니다.
반대로 단점은 미들웨어에 의존하기에 미들웨어에서 제대로 처리를 해주지 않으면 곤란하고, 유저 데이터가 어떤 형식으로 삽입되어 있는지 직접 미들웨어를 확인하지 않으면 알수 없습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +    await session.commit()
await으로 기다리는 함수의 coroutine동작을 완료하고 값을 yield해 주는 것을 async함수 스코프에 한해 대기하게 됩니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="존재하지 않는 포스트입니다"
리소스를 찾을 수 없으니 404 Not Found가 더 적절할 것 같습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +    if post == None:
네. 알겠습니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +            status_code=status.HTTP_400_BAD_REQUEST,
접근 권한이 없다는 의미이기에 403 Forbidden이 더 적절할 것 같습니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +    await session.delete(post)
그냥 delete는 리소스를 제거하는 것이고, 소프트 delete는 리소스에 is_deleted 처럼 상태를 두어서 마치 제거된 것 처럼 취급하는 방식으로 알고있습니다.
소프트 delete는 삭제되어도 일정기간동안 해당 리소스를 유지해야 하거나 리소스를 다른 별도의 테이블로 옮겨 히스토리를 남길때 활용합니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/user.py
> +        raise HTTPException(status_code=400, detail="Invalid password")
네. 알겠습니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/schemas/post.py
> +    created_at: Optional[datetime] = None
네. 추가하겠습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/schemas/user.py
> +class User(BaseModel):
네 알겠습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/database.py
> +    yield
매 실행마다 db가 초기화 된다는 점을 명시하고 싶었습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/models/post.py
> +    user: User = Relationship(back_populates="posts")
관계형으로 묶였기에 모델을 수정해야 할 것 같습니다. user_id는 관계를 표현하기 위한 것이었는데, 사실상 author 역할도 하는 듯합니다. post db모델에서는 author 컬럼을 제거하고 요청에 응답할 때 post도메인 객체에 author를 넣는 방식도 고려하고 있습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +    post = result.one()
NoResultFound 예외가 발생합니다. 예외를 처리하는 중간 단계를 추가하겠습니다.

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/routers/post.py
> +        .join(UserModel, PostModel.user_id == UserModel.id)
user와 post를 각각 불러와서 진행하거나 어차피 필요한건 user_id이니 조인 없이 필드에 있는 user_id를 사용해도 될 것 같습니다

2024-07-01 05:04 UTC, ksg9482-kouno commented on src/models/user.py
> +    posts: list["Post"] = Relationship(back_populates="user")
별도로 설정을 해두지 않으면 자동으로 join이 되지 않는것으로 알고 있습니다.

2024-07-02 14:27 UTC, f-lab-ydrah approved these changes
👍

2024-07-02 14:27 UTC, merged