1-9. FastAPI로 게시글 REST API 서버 구현하기 - Docker Compose로 로컬에서 실행하기
f-lab-edu/fastapi-post pull request #12
Opened 2024-08-20 13:20 UTC by ksg9482

* todo 반영
* 테스트 코드 환경 변수 분리
* dockerfile, docker-compose 생성
* readme.md 수정

2024-08-20 14:48 UTC, f-lab-ydrah requested changes
코멘트 확인해주세요~

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/apis/comment.py
> +    if (not post_id) and (not user_id):
`post_id` , `user_id`가 없어도 API 응답은 나와야 함.

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/apis/comment.py
> +    comments = await service.get_comments_by_id(
메서드명이 오해의 소지가 있음.

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/apis/post.py
> +async def get_get_posts(
```suggestion
async def get_posts(
```

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/apis/user.py
>      delete_session(session_id)
얘는 어느 레이어? 예외를 낸다면, 올바른 레이어에 있는게 맞을까?

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/auth.py
> +session_data: dict[str, SessionContent] = {}
얘도 DB로 옮기면..!

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/auth.py
> -    is_expired = datetime.now(tz=timezone.utc) >= session_data["expire"]
유효기간 지난 경우 로그인 어떻게 하죠? ㅋㅋ

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/database.py
> +from dotenv import load_dotenv
import 문 포매팅이 안되어 있는듯

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/database.py
> +from dotenv import load_dotenv
`pre-commit run`

2024-08-20 14:48 UTC, f-lab-ydrah commented on src/database.py
> +DATABASE_URL = os.environ["DATABASE_URL"]
`class Config(BaseSettings)` 로 설정 클래스 만들어보고 적용하기. 그리고 dotenv 안쓰기

https://docs.pydantic.dev/latest/concepts/pydantic_settings/

2024-08-20 15:21 UTC, merged

2024-08-25 13:45 UTC, viva-rim commented on src/apis/comment.py
> +    if (not post_id) and (not user_id):
메서드명을 더 일반화(get_comments)하여 post_id , user_id은 옵션인 것이 더 명확해지도록 수정하겠습니다

2024-08-25 13:46 UTC, ksg9482 commented on src/apis/comment.py
> +    comments = await service.get_comments_by_id(
get_comments_by_id은 post_id , user_id가 없어도 동작해야 한다는 리뷰의 연장선이라 옵션 입력이 없어도 동작하도록 하겠습니다. 옵션이 없을 경우 모든 코멘트를 반환합니다.

2024-08-25 13:49 UTC, ksg9482 commented on src/apis/user.py
>      delete_session(session_id)
delete_session으로 함수화 했지만 동작이 api에서 service에 걸쳐있었기 때문에 레이어가 모호해졌습니다. 세션을 검증하여 HTTPException을 발생시키는 부분은 logout api에서 처리하도록 하고 세션 저장소에 접근하는 것은 service에서 처리하도록 분리하겠습니다.

2024-08-25 13:54 UTC, ksg9482 commented on src/auth.py
> +session_data: dict[str, SessionContent] = {}
세션관리용 DB를 따로 두는 것도 고려해보았는데 지금 단계에선 그만한 복잡성을 감당하는 것은 낭비라 판단했습니다. 우선 session테이블을 최대한 간단히 만들어서 관리하는 방향으로 진행하겠습니다.

2024-08-25 13:57 UTC, ksg9482 commented on src/auth.py
> -    is_expired = datetime.now(tz=timezone.utc) >= session_data["expire"]
유효기간이 지난 세션임을 알리고 재 로그인을 요청하는 에러메시지를 보냅니다. 기간이 지난 세션이면 바로 재생성해서 주는 것도 고민해보았는데 그러면 제대로 인증이 안되고 세션에 유효기간을 설정한 의미도 없다고 생각해서 재로그인을 요청하는 방향이 맞다고 생각했습니다

2024-08-25 13:59 UTC, ksg9482 commented on src/database.py
> +from dotenv import load_dotenv
pre-commit run을 해도 변동이 없는 것을 보아 설정을 잘못했거나 한 거 같습니다. 이건 조금 더 신경 쓰거나 pre-commit에서 더 확인해보겠습니다.

2024-08-25 13:59 UTC, ksg9482 commented on src/database.py
> +DATABASE_URL = os.environ["DATABASE_URL"]
pydantic_settings 도입하고, 앱 이미지 만들 때 환경 변수 주입으로 처리하겠습니다