[Feature/mypy] mypy 포맷팅
f-lab-edu/fastapi-post pull request #15
Opened 2024-08-29 14:56 UTC by ksg9482

* mypt 도입
  * \# type: ignore 주석으로 처리된 부분은 수정 예정
* pre-commit 통합

2024-08-29 14:57 UTC, ksg9482 commented
pre-commit 수정하다가 commit 잘못 누적된 것은 squash로 처리할 예정입니다

2024-09-03 00:39 UTC, f-lab-ydrah requested changes
코멘트 확인 부탁드립니다~

2024-09-03 00:39 UTC, f-lab-ydrah commented on src/apis/comment.py
> +            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
이건 어떤 경우일까요?
실제 운영 중에 이 에러가 발생한다면, 뭐가 문제인지 어떻게 알 수 있을까요?

2024-09-03 00:39 UTC, f-lab-ydrah commented on src/auth.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="세션 만료 기한이 없습니다."
좋은 에러 메시지는 어떤 것일까요?

2024-09-03 01:02 UTC, ksg9482 commented on src/apis/comment.py
> +            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
myqy 적용하면서 추가된 부분입니다. create_comment 메서드로 새 포스트를 생성하면 comment 객체가 반환되는데 그 객체의 id가 None을 허용하는 옵셔널 타입 입니다. 

객체 타입만 보면 None 타입이 포함되어 있어 None 타입을 받지 않는 CreateCommentResponse와 타입에러를 방지하는 역할입니다.

하지만 db에 저장하고 갱신된 객체를 반환하는데 db연결 문제가 아니고서야 id가 없는 경우가 있을지는 잘 모르겠습니다.

만약 해당 에러 메시지를 수정한다면 코멘트에 id가 None이라고 명시해주는 것이 좋을듯 합니다.

2024-09-03 01:10 UTC, ksg9482 commented on src/auth.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="세션 만료 기한이 없습니다."
myqy 적용하면서 추가된 부분입니다. expire가 옵셔널 타입이라 타입 에러 방지용입니다. 

이 문제도 이미 expire에 값을 넣었지만 None 타입 문제가 발생해서 guard절을 앞에 두었습니다.

이해를 돕기위해 세션 만료 기한이라는 단어를 선택했는데 expire라고 속성명을 확실히 해주는게 좋을까요? 

상태 코드 400은 expire 인수가 제공되지 않을경우 발생하는 문제이기 때문에 해당 코드를 선택했습니디ㅡ

2024-09-03 01:15 UTC, f-lab-ydrah commented on src/apis/comment.py
> +            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
요거는 이따가 멘토링 시간에 다시 얘기해보시죠!

2024-09-03 01:15 UTC, f-lab-ydrah commented on src/auth.py
> +            status_code=status.HTTP_400_BAD_REQUEST, detail="세션 만료 기한이 없습니다."
요것도 이따가 다시 얘기해보시죠 ㅎㅎ

2024-09-03 01:15 UTC, f-lab-ydrah approved these changes
👍

2024-09-03 01:23 UTC, merged